### ISSUE TITLE
Use application package in standalone-integration

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#10]
To verify that the standalone **application** works correctly it would be good if the **standalone-integration** tests ran with the application instead of instantiating the **core** package immediately.

**Comment by masokol** [comment]
I've investigated this a bit. As of now, ecChronos standalone tests are mocking things like table size, metrics etc. This won't be possible with running "application" directly in the tests, meaning that for some tests we will need to have some actual data.

I'm not really sure if this issue is still relevant, python-integration-tests are using the application package. Wdyt @emolsson ?
