### ISSUE TITLE
Don't release test-jar from core module

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#167]
Currently the test JAR from the core module is part of the release and has to be manually removed in the staging area.

We should not include the test jar artifact while deploying.

**Comment by ch1bbe** [comment]
The problem seems to be that the rest project depends on some of the package in the test-jar (core project), so its not possible to exclude or not attache the test-jar when doing a release.

When a release is made and the rest project is built. It will not be satisfied and will fail if the test-jar for the same version ($project.version) is not available.

A way forward could be to move the dependent classes to src/main/java for the core project so they are included in the default jar.
Then it may be possible to put the build configuration for the test-jar in a profile that is only activated for a normal build, not a release.

**Comment by masokol** [comment]
The PR didn't help, the bug is still there.
