### ISSUE TITLE
Excessive logging for tables IN_QUEUE

### ISSUE THREAD

**Issue by etedpet** [Ericsson/ecchronos#191]
When ecChronos have a lot todo (tables IN_QUEUE), a lot of (redundant) logging  is done on info-level:
```
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.491Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl] Table keyspace99.keyvalue last repaired at 2021-03-02 09:34:31, next repair 2021-03-02 10:34:31"}
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.491Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.fm.impl.LoggingFaultReporter] Ceasing alarm: REPAIR_WARNING - {TABLE=keyvalue, KEYSPACE=keyspace99}"}
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.493Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl] Table keyspace99.keyvalue last repaired at 2021-03-02 09:34:31, next repair 2021-03-02 10:34:31"}
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.493Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.fm.impl.LoggingFaultReporter] Ceasing alarm: REPAIR_WARNING - {TABLE=keyvalue, KEYSPACE=keyspace99}"}
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.495Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl] Table keyspace99.keyvalue last repaired at 2021-03-02 09:34:31, next repair 2021-03-02 10:34:31"}
{"version":"0.3.0","timestamp":"2021-03-02T11:19:38.495Z","severity":"info","message":"[com.ericsson.bss.cassandra.ecchronos.fm.impl.LoggingFaultReporter] Ceasing alarm: REPAIR_WARNING - {TABLE=keyvalue, KEYSPACE=keyspace99}"}
```
Not that "the same" entries are written multiple times

- "Table keyspace99.keyvalue last repaired" x 3
- "Ceasing alarm" x 3. But there is no warning to start with (nothing to cease).

This seems to be printed for every table IN_QUEUE and repeatedly.

**Comment by itskarlsson** [comment]
I made some generic fixes in how we handle logging and improved the alarm handling to only cease alarms when they have been raised. I believe this will cut down much of the noise, but I believe the reason you see such messages so often is because the repair interval has been set to a very low value. (Perhaps some sort of test scenario?) 

It is very much intended that the repairedAt time is updated continuously and that such logging messages will be commonplace. All tables have different repairedAt's, so it is also intended that they all keep track of their own time.

I will close this issue for the time being with those two fixes I have made. Hopefully the reduced noise will make things more clear.
